bradesco:
  totalRemessas:
  convenios:
    SEQ:
      convenio:
      agencia:
      conta:
      digitoAgencia:
      carteira:
        nome:
      orgao:
        pessoa:
          cpfCnpj:
        municipio:
          nome:
          uf:
        descricao:
        responsavel:
  transacoes:
    SEQ:
      dam:
        SEQ:
          nossoNumero:
          numeroDocumento:
          valor:
          dataVencimento:
          dataEmissao:
          pessoa:
            cpfCnpj:
            nome:
            endereco:
            cep:

sicoob:
  totalRemessas:
  convenios:
    SEQ:
      agencia:
      digitoAgencia:
      cedente:
      convenio:
      conta:
      orgao:
        pessoa:
          cpfCnpj:
        descricao:
  transacoes:
    SEQ:
      dam:
        SEQ:
          dataVencimento:
          dataEmissao:
          nossoNumero:
          numeroDocumento:
          valor:
          pessoa:
            cpfCnpj:
            nome:
            endereco:
            bairro:
            cep:
            municipio:
              nome:
              uf:
                sigla:
cef:
bb:
  totalRemessas:
  convenios:
    SEQ:
      agencia:
      digitoAgencia:
      cedente:
      convenio:
      conta:
      orgao:
        pessoa:
          cnpj:
        descricao:
  transacoes:
    SEQ:
      dam:
        SEQ:
          dataVencimento:
          dataEmissao:
          nossoNumero:
          numeroDocumento:
          valor:
          pessoa:
            cpfCnpj:
            nome:
            endereco:
            bairro:
            cep:
            municipio:
              nome:
              uf:
                sigla:
